=== sipabrei/fuseHandler/source/test1/src/main/resources/de/hszg/xml/fuse/xsd/MainProductSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/MainProductSchema"
	xmlns:tns="http://www.example.org/MainProductSchema">
	<element name="product" type="tns:productTyp"/>
	<complexType name="productTyp">
		<sequence>
			<element name="name" type="string" />
			<element name="provider" type="string" />
			<element name="supplier" type="string" />
			<element name="product-supplier-id" type="string" />
			<element name="description" type="string" />
			<element name="group" type="tns:groupDef" />
			<element name="price" type="tns:priceTyp" />
			<element name="image" type="anyURI" />
		</sequence>
	</complexType>
	<simpleType name="priceTyp">
		<restriction base="string">
			<pattern value="[1-9]\d*.\d{2}|0.\d{2}" />
		</restriction>
	</simpleType>
	<complexType name="groupDef">
		<attribute name="sub" type="string" />
	</complexType>
</schema>

=== sipabrei/fuseHandler/source/test1/src/main/resources/de/hszg/xml/fuse/xsd/MainProductSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:product xmlns:tns="http://www.example.org/MainProductSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/MainProductSchema MainProductSchema.xsd ">
  <name>name</name>
  <provider>provider</provider>
  <supplier>supplier</supplier>
  <product-supplier-id>product-supplier-id</product-supplier-id>
  <description>description</description>
  <group/>
  <price>price</price>
  <image>http://tempuri.org</image>
</tns:product>
