=== sipabrei/fuseHandler/xmls/openESB/response_search.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/response_search"
    xmlns:tns="http://xml.netbeans.org/schema/response_search"
    elementFormDefault="qualified">
    <xsd:complexType name="results">
        <xsd:sequence>
            <xsd:element name="result" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="maingroup">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="subgroup">
                                        <xsd:complexType>
                                            <xsd:sequence>
                                                <xsd:element name="product">
                                                    <xsd:complexType>
                                                        <xsd:sequence>
                                                            <xsd:element name="pic" type="xsd:string"/>
                                                            <xsd:element name="price" type="xsd:string"/>
                                                            <xsd:element name="description" type="xsd:string"/>
                                                            <xsd:element name="quantity" type="xsd:unsignedInt"/>
                                                            <xsd:element name="attributes">
                                                                <xsd:complexType>
                                                                    <xsd:sequence>
                                                                        <xsd:element name="attribute" minOccurs="0" maxOccurs="unbounded">
                                                                            <xsd:complexType>
                                                                                <xsd:sequence>
                                                                                    <xsd:element name="attributetype" type="xsd:string"/>
                                                                                    <xsd:element name="attributecontent" type="xsd:string"/>
                                                                                </xsd:sequence>
                                                                            </xsd:complexType>
                                                                        </xsd:element>
                                                                    </xsd:sequence>
                                                                </xsd:complexType>
                                                            </xsd:element>
                                                        </xsd:sequence>
                                                        <xsd:attribute name="id" type="xsd:string"/>
                                                    </xsd:complexType>
                                                </xsd:element>
                                            </xsd:sequence>
                                            <xsd:attribute name="name" type="xsd:string"/>
                                        </xsd:complexType>
                                    </xsd:element>
                                </xsd:sequence>
                                <xsd:attribute name="name" type="xsd:string"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="root">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="results" type="tns:results"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== sipabrei/fuseHandler/source/test1/src/test/resources/testData/handler1/singleResponse1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:root xmlns:ns1="http://xml.netbeans.org/schema/response_search" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.netbeans.org/schema/response_search response_search.xsd">
  <ns1:results>
<ns1:result>
      <ns1:maingroup name="Hygieneartikel">
        <ns1:subgroup name="Rasierer">
          <ns1:product id="ra_1">
            <ns1:pic />
            <ns1:price>64.99</ns1:price>
            <ns1:description>Philips PT860/16 Rasierer PowerTouch Plus</ns1:description>
            <ns1:quantity>49</ns1:quantity>
            <ns1:attributes>
              <ns1:attribute>
                <ns1:attributetype>Info1</ns1:attributetype>
                <ns1:attributecontent>Über 50 Minuten kabellose Rasur</ns1:attributecontent>
              </ns1:attribute>
              <ns1:attribute>
                <ns1:attributetype>Info2</ns1:attributetype>
                <ns1:attributecontent>vollständig abwaschbar</ns1:attributecontent>
              </ns1:attribute>
              <ns1:attribute>
                <ns1:attributetype>Info3</ns1:attributetype>
                <ns1:attributecontent>Dual Precision entfernt selbst kürzeste Bartstoppel</ns1:attributecontent>
              </ns1:attribute>
              <ns1:attribute>
                <ns1:attributetype>Info4</ns1:attributetype>
                <ns1:attributecontent>Dynamische Konturenanpassung</ns1:attributecontent>
              </ns1:attribute>
            </ns1:attributes>
          </ns1:product>
        </ns1:subgroup>
      </ns1:maingroup>
    </ns1:result>
  </ns1:results>
</ns1:root>
